#!/usr/bin/env python3

#  Main program.

from dynamodb_demonstration import occultation_count_by_mission


if __name__ == "__main__":

    import argparse

    parser = argparse.ArgumentParser( description="Count RO soundings by mission " + \
            "in a given time interval and store counts in an output JSON file." )

    parser.add_argument( "start_year", type=int, help="The year in which to begin the counting." )
    parser.add_argument( "end_year", type=int, help="The last year of counting the soundings." )
    parser.add_argument( "output_json", type=str, help="The name of the output JSON file." )

    args = parser.parse_args()

    alldata = occultation_count_by_mission( args.start_year, args.end_year, args.output_json )


    pass

