#!/usr/bin/env bash

export FFLAGS="-I/-I${ROPP_ROOT}/gfortran/include -I/usr/include -I/opt/include -g"

# Use included EGM96 geoid, WGS84 ellipsoid, and MSIS files
mkdir  $ROPP_ROOT/data
tar -xzf /mnt/base-image/data.tar.gz 
cp -a /mnt/data $ROPP_ROOT/data
export GEOPOT_COEF=$ROPP_ROOT/data/egm96.dat
export GEOPOT_CORR=$ROPP_ROOT/data/corrcoeff.dat

#  Build ropp_io
cp -a /mnt/installer/ROPP/ropp-11.0/ropp_io ${ROPP_ROOT}
cd ${ROPP_ROOT}/ropp_io
## Redo automakes
# uncomment if you need to create a new module and edit automakes
#aclocal -I m4 --force
#automake -a -c
#autoconf
# Run actual build 
./configure --prefix=${1-$ROPP_ROOT/gfortran} --without-sofa
make 
make install


#  Build ropp_pp
cp -a /mnt/installer/ROPP/ropp-11.0/ropp_pp ${ROPP_ROOT}
cd ${ROPP_ROOT}/ropp_pp 
aclocal -I m4 --force
automake -a -c
autoconf

./configure --without-sofa
make 
make install

