#!/usr/bin/env bash

export FFLAGS="-I/-I${ROPP_ROOT}/gfortran/include -I/usr/include -I/opt/include -g"

# Use included EGM96 geoid, WGS84 ellipsoid, and MSIS files
#tar -xzf $ROPP_ROOT/ropp_pp/data/corrcoef.dat.gz
#tar -xzf $ROPP_ROOT/ropp_pp/data/egm96.dat.gz
#cp -a /mnt/data $ROPP_ROOT/data
export GEOPOT_COEF=$ROPP_ROOT/ropp_pp/data/egm96.dat
export GEOPOT_CORR=$ROPP_ROOT/ropp_pp/data/corrcoeff.dat

#  Build ropp_io
cp -a /mnt/installer/ROPP/ropp-11.0/ropp_io ${ROPP_ROOT}
cd ${ROPP_ROOT}/ropp_io
# Redo automakes to include aws2ropp
aclocal -I m4 --force
automake -a -c
autoconf
./configure --prefix=${1-$ROPP_ROOT/gfortran} --without-sofa
make 
make install


#  Build ropp_pp
cp -a /mnt/installer/ROPP/ropp-11.0/ropp_pp ${ROPP_ROOT}
cd ${ROPP_ROOT}/ropp_pp 
aclocal -I m4 --force
automake -a -c
autoconf

./configure --without-sofa
make 
make install

