
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-11T14:51:45-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "dfa1cd28467541cfafb25056a0402a49bacd219a",
 "version": "2022.01.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
